version: 2
 
models:
  - name: orders
    description: >
      Stores transactional order-level data for all tenants.

      Each record represents a single customer order and includes
      order value, lifecycle status, and creation timestamp.
      This model is used as a core fact table for revenue
      and order analytics.

    columns:
      - name: order_id
        description: >
          Unique identifier for each order.
          Used as the primary key for the orders table.
        data_tests:
          - not_null
          - unique
 
      - name: order_amount
        description: >
          Monetary value of the order.
          Must be zero or positive and represents the total
          amount charged for the order.
        data_tests:
          - not_null
 
      - name: status
        description: >
          Current lifecycle status of the order.
          COMPLETED indicates a successfully fulfilled order,
          while CANCELLED indicates an order that was not fulfilled.
        data_tests:
          - accepted_values:
              values: ['COMPLETED', 'CANCELLED']
 
      - name: tenant_id
        description: >
          Identifier for the tenant or client that owns the order.
          Used to support multi-tenant data isolation and analytics.
        data_tests:
          - not_null
 
      - name: created_at
        description: >
          Timestamp indicating when the order was created in the system.
          Used for time-based analysis such as daily revenue trends
          and order volume tracking.
        data_tests:
          - not_null
 
 
  - name: customers
    description: >
      Stores master customer data across all tenants.

      Each record represents a unique customer and includes
      their current lifecycle status. This model is commonly
      joined with orders to perform customer-level analytics.

    columns:
      - name: customer_id
        description: >
          Unique identifier for each customer.
          Acts as the primary key for the customers table.
        data_tests:
          - not_null
          - unique
 
      - name: customer_status
        description: >
          Current status of the customer account.
          ACTIVE customers are eligible to place orders,
          while INACTIVE customers are no longer active.
        data_tests:
          - accepted_values:
              values: ['ACTIVE', 'INACTIVE']
