version: 2

models:
  - name: stg_orders
    description: "Staging orders model from TPCH sample data"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

  - name: fct_lineitem_heavy
    description: "Heavy fact model used to simulate warehouse spillage"
